### PR TITLE
Implement respawn command

### LINKED ISSUE #113: Add respawn command

### PR DESCRIPTION
**Pull request by Jaguar-515**
This PR closes #113.

### CODE REVIEW

**Comment by evaera** [comment]
Great! Please remove the comments on the top of each file and rename `victims` to `targets`.

**Comment by Jaguar-515** [comment]
Just did that, should be ready to merge!

**Comment by evaera** [comment]
Sorry, one more thing. Could you please update the docs to list this new default command?

**Comment by Jaguar-515** [comment]
Unless I missed something, it should be ready to merge. ¯\_(ツ)_/¯

**Comment by evaera** [comment]
Haha. One more thing, just realized. The command doesn't have any output. Could you add an acknowledgement like in the other commands (telling number of players respawned)?

And sorry for not noticing this earlier. Could have saved you a bit of time if I had :P

**Comment by Jaguar-515** [comment]
After several changes suggested by you, I think it's time to merge this PR.

**Comment by evaera** [comment]
Looks good. Thanks.

**Pull request merged**
