### PR TITLE
Fix Cmdr GUI replicating twice

### PR DESCRIPTION
**Pull request by y3th**
#125

### CODE REVIEW

**Comment by evaera** [comment]
I am not sure that this fixes the issue. Player GUI is cloned when the character first spawns. It seems like the code you've put here could still end up putting the GUI in the player twice.

**Comment by y3th** [comment]
Looks fine when I test it.

```lua
-- Client
local ReplicatedStorage = game:GetService("ReplicatedStorage")
require(ReplicatedStorage:WaitForChild("CmdrClient"))
```

```lua
-- Server
require(script.Cmdr)
```

image

**Comment by y3th** [comment]
Turns out it does replicate twice when loading Cmdr before loading the character. Will fix this.

```lua
-- Server
local Players = game:GetService("Players")

Players.PlayerAdded:Connect(function(player)
	wait(10)
	player:LoadCharacter()
end)

wait(5)

require(script.Cmdr)
```

image

**Comment by y3th** [comment]
Just realized there's a simpler solution, closing PR for now.

**Comment by y3th** [comment]
Made a new pull request at #151.

**Pull request closed without merging**
