### PR TITLE
Ban command

### PR DESCRIPTION
**Pull request by ImmortalSlayer**
The following request is a created ban command that ban a user for a certain amount of time (using the new duration type) as well as a given reason.

### CODE REVIEW

**Comment by LoganDark** [comment]
Most games have their own ban system. Integrators of Cmdr would most likely create one of their own.

Taking a quick glimpse of your code, I don't think it fits the theme of the other default commands.

**Comment by AnonymousDeveloper13** [comment]
I honestly disagree and feel like a default system should be in place but you could modify it if you want to work with your own ban system

**Comment by evaera** [comment]
If there was a ban system, it wouldn't be modifiable. The best you could do is just not register it and make your own. Cmdr's built in commands should never be modified manually.

**Comment by LoganDark** [comment]
@evaera Maybe a ban system could serve as an example, but not a default feature of Cmdr.

**Pull request closed without merging**
