### PR TITLE
Replace TeleportPartyAsync with TeleportAsync

### PR DESCRIPTION
**Pull request by wilyt1**
TeleportPartyAsync can only teleport to a place in the same universe. I replaced it with the new TeleportAsync, which can teleport to places in a different universe.

### CODE REVIEW

**Comment by evaera** [comment]
Will this keep the same group of players together on the other end?

**Comment by wilyt1** [comment]
Unfortunately, I could not find anything regarding teleporting players to the same server instance on the DevHub.

**Comment by Hexcede** [comment]
> Will this keep the same group of players together on the other end?

No, it would need to conditionally fall back to `TeleportAsync` when the target place is not in the same universe.

**Comment by evaera** [comment]
Let's revert this PR back to the original commit (just simply replacing the function) and merge.

**Comment by wilyt1** [comment]
I have reverted the pull request to the original commit.

**Pull request merged**
