### PR TITLE
Update Dispatcher.lua to be Roblox compliant

### PR DESCRIPTION
**Pull request by railworks2**
Third party links (such as this) are not acceptable under 11. Other activities of the Roblox Community rules.

I wouldn't want Cmdr to be taken down over such an oversight

### CODE REVIEW

**Comment by evaera** [comment]
This error message is only displayed in Studio, so I believe it's already compliant with the rules.

**Comment by railworks2** [comment]
I'm not aware of any expectations related to this being in studio. 

Given it's code present in a production module, I would expect to meet all of the Roblox Terms.

**Comment by evaera** [comment]
This isn't going to cause moderation action against anyone. Having a link is very useful for beginners and I don't think there's any tangible value from removing it here. If it bothers you, feel free to remove it from your own copy.

**Comment by enescglyn** [comment]
you are most craziest guy i have ever seen in your roblox profile's description you literally link your website and break roblox rule 11

**Comment by enescglyn** [comment]
im surprised that roblox put you onto their post approval team

**Pull request closed without merging**
